name: Test Lichess Token

on:
  workflow_dispatch: # manuelles Starten möglich

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Arena Maker
        run: OAUTH_TOKEN=${{ secrets.LICHESS_TOKEN }} yarn dev
